// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ErwinMayerLabs.DisableNoSourceAvailableTab
{
    internal sealed partial class Vsix
    {
        public const string Id = "5126c493-138a-46d7-a04d-ad772f6be155";
        public const string Name = "Disable Break Mode & No Source Available Tab";
        public const string Description = @"This small extension will prevent the tool window with title 'No Source Available' or 'Break Mode' from appearing in Visual Studio, and preserve the focus on the currently active tab.

Alas, Visual Studio otherwise displays a tab stating that 'The application is in break mode' and that it cannot find source code to step into. This is obvious when simply pausing an idle application, therefore it forces the developer to close this window before getting back to the code he wants to modify, which may be a productivity killer. 

Let's hope this extension will be short-lived (though it has been more than 10 years now :) as the Visual Studio development team adds an option to better control this behavior!

This extension should work with all locales of Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "4.0.2";
        public const string Author = "Erwin Mayer";
        public const string Tags = "Break Mode, The application is in break mode, Debugger, debugging, no source available, hide window, Quelle verfügbar, sources disponibles, Aucune source disponible";
    }
}
