// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ErwinMayerLabs.DisableNoSourceAvailableTab
{
    static class Vsix
    {
        public const string Id = "5126c493-138a-46d7-a04d-ad772f6be155";
        public const string Name = "Disable No Source Available Tab";
        public const string Description = @"This small extension will prevent the tool window with title 'No Source Available' from appearing in Visual Studio, and preserve the focus on the currently active tab.

Alas, along with brilliant improvements such as IntelliTrace, Visual Studio otherwise displays a tab stating that it cannot find source code where to step into. This is obvious when simply pausing an idle application, therefore it forces the developer to close this window before getting back to the code he wants to modify, which may be a productivity killer. 

Let's hope this extension will be short-term lived as the Visual Studio development team adds an option to better control this behavior!

This extension should work with all locales of Visual Studio.";
        public const string Language = "en-US";
        public const string Version = "3.2";
        public const string Author = "Erwin Mayer";
        public const string Tags = "Debugger, debugging, no source available, hide window, Quelle verfügbar, sources disponibles, Aucune source disponible, break mode";
    }
}
